config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  root "home#index"

  resources :news, path: :publications

  delete "/publications/:id/remove_thumbnail", to: "news#remove_thumbnail"

  scope "/profile" do
    get "/publications", to: "profile#publications"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  has_one_attached :avatar
end

app/models/news.rb
class News < ApplicationRecord
  after_validation :set_slug, only: [:create, :update]

  has_one_attached :thumbnail

  validates_presence_of :content, message: "You can't create a publication without any content"
  validates_presence_of :title, message: "Title is required"

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = title.to_s.parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news = News.where(published: true)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  def index

  end

  def show
    dom_sanitizer = Rails::Html::SafeListSanitizer.new
    @news = News.find_by(id: params[:id])
    @news.content = dom_sanitizer.sanitize(@news.content, attributes: %w(id class style))
  end

  def new
    @news = News.new
  end

  def create
    puts("params", publication_params)

    @news = News.create publication_params
    @news.user_id = current_user[:id]

    @news.thumbnail.attach(publication_params[:thumbnail])

    if @news.save
      redirect_to news_path(id: @news.id)
    else
      @errors = @news.errors.messages[:content][0]
      puts("@errors", @errors)
    end
  end

  def edit
    @news = News.find_by(id: params[:id])
  end

  def update
    @news = News.find_by(id: params[:id])

    if @news.update publication_params
      redirect_to news_path(id: @news.id)
    else
      @errors = @news.errors.messages[:content][0]
      puts("@errors", @errors)
    end
  end

  def destroy
    news_id = params[:id]
    puts("news_id", news_id)

    @news = News.find_by(id: news_id)

    puts("@news", @news.to_json)

    nil unless @news.present?

    if @news.destroy
      redirect_to root_url
    end

  end

  def remove_thumbnail
    @news = News.find_by(id: params[:id])
    if @news.thumbnail.attached?
      @news.thumbnail.attachment.purge

      redirect_back fallback_location: edit_news_path(id: params[:id])
    end
  end

  private

  def publication_params
    params.require(:publication).permit(:content, :published, :thumbnail, :reading_time, :title)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def publications
    puts "current_user[:id]", current_user[:id]
    # @news = News.find_by(user_id: current_user[:id])
    # @news = News.find_by_user_id current_user[:id]
    @news = News.where(user_id: current_user[:id])
    puts "@news", @news.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/application/home.html.erb
<%= render "layouts/navbar" %>

<main>
  <div class="w-full w-100 d-flex justify-content-center mt-5">
    <h1 class="dp-title dp-title__large bold">Todays News</h1>
  </div>
</main>

app/views/home/index.html.erb
<%= render "layouts/navbar" %>

<main class="h-100">
  <div class="w-full w-100 d-flex justify-content-center mt-5">
    <h1 class="dp-title dp-title__large bold">Todays News</h1>
  </div>

  <%= render partial: "news/list", locals: { publications: @news, empty_list_message: "Nothing to read today", user_is_managing: false } %>
</main>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light px-5 pt-4">
  <div class="container-fluid">
    <a class="dp-subtitle text-dark" href="<%= root_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Settings</a></li>
              <li><a class="dropdown-item" href="<%= publications_url %>">My articles</a></li>
              <li><hr class="dropdown-divider"></li>
              <li class="d-flex justify-content-center align-items-center">
                <%= link_to destroy_user_session_url, { method: :delete } do %>
                  <button type="button" class="btn btn-dark">Sign out</button>
                <% end %>
              </li>
            </ul>
          </li>
          <% unless controller_name == "news" && action_name == "new" %>
            <li class="nav-item ms-3">
              <%= link_to new_news_url do %>
                <button type="button" class="btn btn-dark">Create publication</button>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item me-4">
            <a href="<%= new_user_registration_url %>">
              <button type="button" class="btn btn-dark">Create account</button>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_url %>">
              Login
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Danspaper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- tiny mce -->
    <script src="https://cdn.tiny.cloud/1/86s9a5sksti2mk3k9lzmq98vb2m1i242vkemzjk3ol3wxng0/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <!-- animate.css -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />

    <!-- bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>

  <body class="h-100">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </symbol>
      <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
      </symbol>
      <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </symbol>
    </svg>

    <% if notice %>
      <div class="alert alert-primary d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
        <div>
          <%= notice %>
        </div>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Error:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          <%= alert %>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/news/_card.html.erb
<a class="publication-card" href="<%= news_path id: "#{publication.id}-#{publication.slug}"  %>">
  <div class="d-flex flex-column align-items-stretch mb-5 <%= user_is_managing ? "card card-body" : "" %>">
    <% unless user_is_managing %>
      <%= render partial: "news/card_thumbnail", locals: { publication: publication } %>
    <% end %>


    <div class="d-flex align-items-center justify-content-between w-100">
      <div class="d-flex align-items-center">
        <h2 class="dp-subtitle"><%= publication.title %></h2>
        <% unless publication.published %>
          <span class="badge bg-warning text-dark ms-3">Draft</span>
        <% end %>
      </div>

      <% if user_is_managing %>
        <div class="d-flex">
          <button
            type="button"
            class="btn btn-link text-danger"
            data-remote="true"
            data-method="delete"
            data-url="<%= news_url id: publication.id %>"
            data-confirm="Are you sure you want to delete this publication?"
          >
            <i class="bi bi-trash-fill"></i>
          </button>

          <a
            type="button"
            class="btn btn-link text-secondary"
            href="<%= edit_news_path id: publication.id %>"
          >
            <i class="bi bi-pencil-fill"></i>
          </a>
        </div>
      <% end %>

    </div>
    <span class="text-secondary"><%= publication.created_at.localtime.strftime("%B %d, %Y - %H:%M") %></span>
  </div>
</a>

<%#= render "news/deletion_confirmation_modal" %>

app/views/news/_card_thumbnail.html.erb
<% if publication.thumbnail.attached? %>
  <img src="<%= publication.thumbnail.attachment.url %>" alt="<%= publication.title %>" class="img-fluid mb-3" />
<% else %>
  <div class="publication-thumbnail d-flex justify-content-center align-items-center bg-dark p-5 mb-3">
    <span class="dp-subtitle__large text-light"><%= publication.title %></span>
  </div>
<% end %>

app/views/news/_deletion_confirmation_modal.html.erb
<div class="modal fade" id="article-delete-modal" tabindex="-1" aria-labelledby="Delete article confirmation" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body text-center mt-5">
        Are you sure you want to delete this publication?
      </div>
      <div class="w-100 d-flex align-items-center justify-content-end p-4">
        <%= form_for @news, url: news_url, method: :delete do %>
          <button type="submit" class="btn btn-danger btn-sm me-3">Yes</button>
        <% end %>
        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

app/views/news/_list.html.erb
<div class="w-100 mw-sm mx-auto px-3 h-100 mt-5">
  <% if !publications.nil? && publications.empty? %>
    <% if empty_list_message.nil? %>
      <p>Nothing to show</p>
    <%  else  %>
      <p><%=  empty_list_message  %></p>
    <% end %>
  <% else %>
    <% publications.each do | publication | %>
      <%= render partial: "news/card", locals: { publication: publication, user_is_managing: user_is_managing } %>
    <% end %>
  <% end %>
</div>

app/views/news/create.js.erb
<% if @errors %>
  console.log("<%= @errors.to_json %>")
<% end %>

app/views/news/edit.html.erb
<%= javascript_pack_tag 'tiny_mce' %>

<%= render 'layouts/navbar' %>

<main class="w-full mt-5 py-5">
  <h1 class="dp-subtitle w-100 mx-auto mw-md px-3 text-center mb-5">Editing publication</h1>

  <% if @news.thumbnail.attached? %>
    <div class="w-100 mx-auto mw-md px-3 mb-5">
      <p class="form-label mb-2">Current thumbnail</p>
      <%= render partial: "news/card_thumbnail", locals: { publication: @news } %>

      <%= form_with url: "/publications/#{@news.id}/remove_thumbnail", method: :delete, class: "mt-3 w-100 mx-auto d-flex align-items-center justify-content-center" do | form | %>
        <button type="submit" aria-label="Delete thumbnail" class="btn btn-danger">Delete thumbnail <i class="bi-trash-fill"></i></button>
      <% end %>
    </div>
  <% end %>

  <%= form_with model: @news, scope: :publication, url: news_path, method: "patch", id: "new-article", local: true do | form | %>
    <div class="w-100 mw-lg mx-auto px-3 mb-4 d-flex flex-column justify-content-start">
      <label class="form-label d-flex flex-column mb-3">
        <span>Title</span>
        <%= form.text_field :title, class: "form-control" %>
      </label>

      <div class="mb-3">
        <label for="thumbnail-picker" class="form-label">Thumbnail</label>
        <%= form.file_field :thumbnail, class: "form-control" %>
      </div>

      <div class="form-check mb-3">
        <%= form.check_box :published, class:"form-check-input", id:"published-check" %>
        <label class="form-check-label" for="published-check">
          Published
        </label>
      </div>

      <label class="form-label d-flex flex-column mb-3">
        <span>Reading time</span>
        <%= form.text_field :reading_time, class: "form-control", placeholder: "How long will users take to read your article? (Ex.: 2 minutes)" %>
        <span class="form-text">Leave it blank if don't want to include this information</span>
      </label>
    </div>

    <div class="w-100 mx-auto mw-lg px-3">
      <%= form.text_area :content, id: "content-editor" %>
    </div>

    <div class="w-100 mw-lg mx-auto d-flex justify-content-end align-items-center px-3 mt-5">
      <button type="submit" class="btn btn-dark">Save</button>
    </div>
  <% end %>
</main>

app/views/news/new.html.erb
<%= javascript_pack_tag 'tiny_mce' %>

<%= render 'layouts/navbar' %>

<main class="w-full mt-5">
  <h1 class="dp-subtitle w-full mx-auto mw-md px-3 text-center mb-5">Create a new publication</h1>


  <%= form_with url: news_index_url, method: :post, id: "new-article", local: false do | form | %>
    <div class="w-100 mw-lg mx-auto px-3 mb-4 d-flex flex-column justify-content-start">
      <label class="form-label d-flex flex-column mb-3">
        <span>Title</span>
        <input type="text" name="publication[title]" class="form-control" />
      </label>

      <%#= react_component("ImageUpload") %>

      <div class="mb-3">
        <label for="thumbnail-picker" class="form-label">Thumbnail</label>
        <%= form.file_field "publication[thumbnail]", class: "form-control" %>
      </div>

      <div class="form-check mb-3">
        <input class="form-check-input" type="checkbox" name="publication[published]" id="published-check">
        <label class="form-check-label" for="published-check">
          Published
        </label>
      </div>

      <label class="form-label d-flex flex-column mb-3">
        <span>Reading time</span>
        <input type="text" name="publication[reading_time]" class="form-control" placeholder="How long will users take to read your article? (Ex.: 2 minutes)" />
        <span class="form-text">Leave it blank if don't want to include this information</span>
      </label>
    </div>

    <div class="w-100 mx-auto mw-lg px-3">
      <textarea id="content-editor" name="publication[content]"></textarea>
    </div>

    <div class="w-100 mw-lg mx-auto d-flex justify-content-end align-items-center px-3 mt-5">
      <button type="submit" class="btn btn-dark">Save</button>
    </div>
  <% end %>
</main>

<!--<div class="toast align-items-center text-white bg-danger border-0 animate__animated" role="alert" aria-live="assertive" aria-atomic="true">-->
<!--  <div class="d-flex">-->
<!--    <div class="toast-body">-->
      <%#= @errors %>
<!--    </div>-->
<!--    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>-->
<!--  </div>-->
<!--</div>-->

app/views/news/read.html.erb
<%= render "layouts/navbar" %>

<main class="w-100 mw-lg mx-auto px-3 mt-5">
  <h1 class="dp-title text-center"><%= @news.title %></h1>

  <div class="w-100 d-flex flex-column justify-content-start">
    <% unless @news.reading_time.blank? %>
      <span class="mb-2"><span class="fw-bold">Reading time:</span> <%= @news.reading_time %></span>
    <% end %>
    <span class="mb-2"><span class="fw-bold">Published at:</span> <%= @news.created_at.localtime.strftime("%B %d, %Y - %H:%M") %></span>

    <% if current_user[:id] == @news.user_id %>
      <div class="mt-3">
        <button type="button" class="btn btn-secondary">Edit</button>
        <button type="button" class="btn btn-danger ms-2" data-bs-toggle="modal" data-bs-target="#article-delete-modal">Delete</button>
      </div>
    <% end %>
  </div>

  <article class="w-full mt-5">
    <%= @news.content.html_safe %>
  </article>
</main>

<% if current_user[:id] == @news.user_id %>
  <%= render "deletion_confirmation_modal" %>
<% end %>

app/views/news/show.html.erb
<%= render "layouts/navbar" %>

<main class="w-100 mw-lg mx-auto px-3 mt-5">

  <% if @news.published.nil? || @news.published == false %>
    <div class="alert alert-warning" role="alert">
      <h4 class="alert-heading">Draft publication</h4>
      <% if current_user.present? && @news.user_id == current_user[:id] %>
        <p>This publication is considered a draft since you didn't choose to save as <strong>published</strong></p>
        <p>This page will not be available through the newsfeed, but can be accessed if someone has the link, so share at your own risk.</p>
      <% else %>
        <p>This is a draft publication. Please be nice to the author and <strong>don't share the link or ask for his permission first</strong></p>
      <% end %>
    </div>
  <% end %>

  <%= render partial: "news/card_thumbnail", locals: { publication: @news } %>

  <h1 class="dp-title text-center"><%= @news.title %></h1>

  <div class="w-100 d-flex flex-column justify-content-start">
    <% unless @news.reading_time.blank? %>
      <span class="mb-2"><span class="fw-bold">Reading time:</span> <%= @news.reading_time %></span>
    <% end %>
    <span class="mb-2"><span class="fw-bold">Published at:</span> <%= @news.created_at.localtime.strftime("%B %d, %Y - %H:%M") %></span>

    <% if current_user.present? && current_user[:id] == @news.user_id %>
      <div class="mt-3">
        <a role="button" class="btn btn-secondary btn-sm" href="<%= edit_news_path %>">Edit</a>
        <button type="button" class="btn btn-danger btn-sm ms-2" data-bs-toggle="modal" data-bs-target="#article-delete-modal">Delete</button>
      </div>
    <% end %>
  </div>

  <article class="w-full mt-5">
    <%= @news.content.html_safe %>
  </article>
</main>

<% if current_user.present? && current_user[:id] == @news.user_id %>
  <%= render "deletion_confirmation_modal" %>
<% end %>